dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
os:
  - osx
cache:
  directories:
    - "node_modules"
before_install:
  - "npm install -g npm@5.0.0 typescript@latest"
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
install:
  - npm install
script:
  - npm run build
